DEPARTMENTS = [
    {
        "key": "police",
        "name": "Police & Law Enforcement",
        "short": "Police",
        "color": "#3b82f6",
        "icon": "shield",
        "desc": "Crime, theft, assault, law & order, traffic violations",
        "password": "police123",
        "officer": "Inspector",
    },
    {
        "key": "fire",
        "name": "Fire & Emergency Services",
        "short": "Fire & Rescue",
        "color": "#ef4444",
        "icon": "flame",
        "desc": "Fires, gas leaks, building collapses, rescue operations",
        "password": "fire123",
        "officer": "Fire Chief",
    },
    {
        "key": "water",
        "name": "Water Supply & Sewerage",
        "short": "Water Supply",
        "color": "#0ea5e9",
        "icon": "droplet",
        "desc": "Water supply, sewerage, drainage, water quality",
        "password": "water123",
        "officer": "Water Engineer",
    },
    {
        "key": "roads",
        "name": "Roads & Infrastructure",
        "short": "Roads & Civil",
        "color": "#f59e0b",
        "icon": "road",
        "desc": "Potholes, road damage, bridges, footpaths, street lighting",
        "password": "roads123",
        "officer": "Civil Engineer",
    },
    {
        "key": "sanitation",
        "name": "Solid Waste & Sanitation",
        "short": "Sanitation",
        "color": "#10b981",
        "icon": "trash",
        "desc": "Garbage collection, sewage overflow, public cleanliness",
        "password": "sanitation123",
        "officer": "Sanitary Officer",
    },
    {
        "key": "electricity",
        "name": "Electricity & Power",
        "short": "Electricity",
        "color": "#eab308",
        "icon": "zap",
        "desc": "Power cuts, voltage issues, electric poles, transformers",
        "password": "electricity123",
        "officer": "Electrical Engineer",
    },
    {
        "key": "health",
        "name": "Public Health & Medical",
        "short": "Health",
        "color": "#ec4899",
        "icon": "medical",
        "desc": "Disease outbreaks, hospitals, food hygiene, mosquitoes",
        "password": "health123",
        "officer": "Health Officer",
    },
    {
        "key": "planning",
        "name": "Urban Planning & Building",
        "short": "Town Planning",
        "color": "#8b5cf6",
        "icon": "building",
        "desc": "Illegal construction, encroachment, building violations",
        "password": "planning123",
        "officer": "Town Planner",
    },
    {
        "key": "environment",
        "name": "Environment & Green",
        "short": "Environment",
        "color": "#22c55e",
        "icon": "leaf",
        "desc": "Pollution, tree cutting, parks, stray animals, wildlife",
        "password": "environment123",
        "officer": "Environment Officer",
    },
    {
        "key": "transport",
        "name": "Public Transport & Traffic",
        "short": "Transport",
        "color": "#f97316",
        "icon": "bus",
        "desc": "Public transport, traffic congestion, parking, signal issues",
        "password": "transport123",
        "officer": "Transport Officer",
    },
    {
        "key": "education",
        "name": "Education",
        "short": "Education",
        "color": "#6366f1",
        "icon": "school",
        "desc": "Public schools, mid-day meals, school infrastructure",
        "password": "education123",
        "officer": "Education Officer",
    },
    {
        "key": "social",
        "name": "Social Welfare",
        "short": "Social Welfare",
        "color": "#14b8a6",
        "icon": "heart",
        "desc": "Homelessness, disability, food assistance, elder care",
        "password": "social123",
        "officer": "Welfare Officer",
    },
]

DEPARTMENT_MAP = {d["key"]: d for d in DEPARTMENTS}

VALID_DEPARTMENTS = [d["name"] for d in DEPARTMENTS]
